[Admin]
Password = ""

[Mama]
Password = "fahrrad schiff zug"

[Papa]
Password = "haus blume mond"

[Yannick]
Password = "hund vogel baum"

[Liv]
Password = "insel schiff zug"

[Linus]
Password = "feuer hund wasser"

[Vroni]
Password = "auto baum wasser"

[Noel]
Password = "sonne erde vogel"

[Gina]
Password = "fisch haus feuer"

[Claus]
Password = "mond stern wasser"

[Oma]
Password = "blume vogel haus"

[Opa]
Password = "zug katze hund"
